bot:
    token: 'ODcwNzYzMzA2Nzc5MDIxMzMy.YQRfhg.oSXhKy9jfwZ9pOrl2Zmk2I_G06E' #token dostępu do bota
    prefix: '*'
    name: 'SpeedRPG'
    adminrank: 869998487612301392 #id rangi, którą posiada administracja
    channel_member_count: 870762860593152000 #id kanału, który ma nosić nazwę z liczbą użytkowników
    channel_new_user: 870762899201728562 #id kanału, który ma nosić nazwę z najnowszym użytkownikiem
    embed_color: 0xb4e1ff #tutaj wpisz kolor, jaki mają posiadać wiadomości typu embed
    synchro_rank: 870003889712279562 #ranga, którą otrzymuje połączone konto z grą
mta:
    ip: '51.83.182.99' #ip serwera mta
    port: 21096 #port serwera mta
mysql:
    host: '137.74.6.118' #uzytkownik bazy danych
    user: 'db_72958' #haslo do bazy danych
    password: 'xwRoVpNdVGQO' #ip bazy danych
    database: 'db_72958' #baza danych


